import "~/styles/globals.css";
import { type Metadata } from "next";
import { Poppins } from "next/font/google";
import { MyRuntimeProvider } from "./MyRuntimeProvider";
import { TRPCReactProvider } from "~/trpc/react";
import { Toaster } from "react-hot-toast";
import { SessionProvider } from "next-auth/react";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "FiscAI",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/fiscaiwhitelogo.png" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <MyRuntimeProvider>
      <html lang="en" className={`${poppins.className}`}>
        <body className="overflow-x-hidden antialiased">
            <Toaster />
            <TRPCReactProvider>{children}</TRPCReactProvider>
        </body>
      </html>
    </MyRuntimeProvider>
  );
}
